modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="neo_lazy_chunks.png"
credits="Original mod by rizen. Ported to NeoForge by Huangjiang-a11y."
authors="Huangjiang-a11y"
description='''
Reduces stutters by spreading chunk loading across multiple frames.
A client-side mod that dynamically throttles chunk processing based on your current FPS.
'''

[[mixins]]
config="neo_lazy_chunks.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"